image: ctcampbelldocker/veracode-ci-examples

stages:
    - build
    - scan

package:
    stage: archive
    script:
        - git archive -o veracode.zip HEAD
    artifacts:
        paths:
            - veracode.zip
    
veracode-policy-scan:
    stage: scan
    only:
        - schedules
        - master
    before_script:
        - wget -q -O veracode-wrapper.jar https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/${VERACODE_WRAPPER_VERSION}/vosp-api-wrappers-java-${VERACODE_WRAPPER_VERSION}.jar
    script:
        - java -jar --add-modules java.se.ee veracode-wrapper.jar -vid ${TEAM_ANALYSISCENTER_ID} -vkey ${TEAM_ANALYSISCENTER_KEY}
          -action UploadAndScan -appname "${CI_PROJECT_NAME}" -createprofile true -autoscan true
          -filepath veracode.zip -version "job ${CI_JOB_ID} in pipeline ${CI_PIPELINE_ID}"
